root = "."
tmp_dir = "tmp"

[build]
# Updated to point to your new main.go in cmd/server
cmd = "go build -o ./bin/app ./cmd/server"
bin = "./bin/app"
include_ext = ["go"]
exclude_dir = ["vendor", "node_modules", "tmp"]
# Runs the binary with any args (like --directory)
full_bin = "./bin/app"

[log]
time = true